http:
  middlewares:
    redirect-web-to-websecure:
      redirectScheme:
        scheme: https
        permanent: true

    headers-secure:
      headers:
        frameDeny: true
        referrerPolicy: no-referrer-when-downgrade
        contentTypeNosniff: true
        xssProtection: "1; mode=block"
        browserXssFilter: true
        forceSTSHeader: true
        stsSeconds: 15552000
        stsIncludeSubdomains: true
        stsPreload: true